### PR TITLE
Proposed edits to index.md

### PR DESCRIPTION
**Pull request by jonathanpollack**
This is still a work in progress. 

A part of #221

### CODE REVIEW

**Comment by pragmadash** [comment]
Related to #227

**Comment by pragmadash** [comment]
I've updated a "Logger" section a little bit, please update your branch.

**Comment by jonathanpollack** [comment]
Updated -- but there is still a fair bit more to go.

**Comment by JuliaRechkunova** [comment]
@jonathanpollack thanks for your help!

**Pull request merged**
