### PR TITLE
Remove logger from the core

### PR DESCRIPTION
**Pull request by pragmadash**
Since we can't provide the best logging experience for everyone
out of the box, it would be better to exclude a logger from the core and
publish separate plugins for several loggers support.

Related to #222.

### CODE REVIEW

**Comment by JuliaRechkunova** [comment]
Are you going to update docs?

**Comment by pragmadash** [comment]
I've updated the docs https://github.com/catberry/catberry/blob/%23221-es6-docs/docs/index.md#logger

**Comment by JuliaRechkunova** [comment]
:+1:

**Comment by JuliaRechkunova** [comment]
Need to update `catberry-homepage` and `catberry-todomvc` after this PR.

**Pull request merged**
