### PR TITLE
add support find coffeescript file extension for store

### PR DESCRIPTION
**Pull request by mass3ff3ct**
I'm added new custom setting storesGlob and update documentation.
Example:

```
//in config file
"storesGlog": "**/*.coffee"  // default: "**/*.js"
```

Old pull request https://github.com/catberry/catberry/pull/203

### CODE REVIEW

**Comment by pragmadash** [comment]
@mass3ff3ct thank you! Nice job.

The only thing we should fix is https://github.com/catberry/catberry/pull/204/files#diff-fac14b908372930c2279a25c773fd436R155 – here we should use `path.extname(p)` instead `.js`.

After that I will merge the PR.

**Comment by mass3ff3ct** [comment]
Sorry, this is my carelessness. Fixed it

**Comment by mass3ff3ct** [comment]
@pragmadash, I see a lot of places in the code that can be improved. Can I send the PR on this issue?

**Comment by pragmadash** [comment]
@mass3ff3ct I don't mind to merge any other PR if it improves the code.

**Pull request merged**
